#!/bin/bash
# >>> CUSTOM: Generate .env from GCP Secret Manager
# This script fetches sensitive secrets from GCP Secret Manager
# and writes them to /opt/actual/.env for Docker Compose.
# Non-sensitive envs are versioned directly in docker-compose.prod.yml.
set -euo pipefail

PROJECT_ID="actual-financas"
ENV_FILE="/opt/actual/.env"

# Secrets to fetch: GCP_SECRET_NAME -> ENV_VAR_NAME
declare -A SECRETS=(
  ["ACTUAL_OPENID_CLIENT_ID"]="ACTUAL_OPENID_CLIENT_ID"
  ["ACTUAL_OPENID_CLIENT_SECRET"]="ACTUAL_OPENID_CLIENT_SECRET"
  ["AI_STUDIO_API_KEY"]="ACTUAL_GEMINI_API_KEY"
)

echo "=== Generating ${ENV_FILE} from GCP Secret Manager ==="

# Start with empty file (non-sensitive envs are in docker-compose.prod.yml)
cat > "${ENV_FILE}" <<'HEADER'
# Auto-generated by generate-env.sh — do NOT edit manually.
# Sensitive values from GCP Secret Manager.
# Non-sensitive config is in docker-compose.prod.yml.
HEADER

ERRORS=0
for SECRET_NAME in "${!SECRETS[@]}"; do
  ENV_VAR="${SECRETS[$SECRET_NAME]}"
  VALUE=$(gcloud secrets versions access latest \
    --secret="${SECRET_NAME}" \
    --project="${PROJECT_ID}" 2>/dev/null) || {
    echo "ERROR: Failed to fetch secret ${SECRET_NAME}"
    ERRORS=$((ERRORS + 1))
    continue
  }
  echo "${ENV_VAR}=${VALUE}" >> "${ENV_FILE}"
  echo "  ✓ ${ENV_VAR} (from ${SECRET_NAME})"
done

chmod 600 "${ENV_FILE}"

if [ "${ERRORS}" -gt 0 ]; then
  echo "WARNING: ${ERRORS} secret(s) failed to fetch"
  exit 1
fi

echo "=== ${ENV_FILE} generated successfully ==="
